project_name: ks
builds:
  - main: ./cmd/ks/main.go
    binary: ks
    ldflags: -X "main.version={{.Version}}" -X "main.apimachineryVersion={{.Env.APIMACHINERY_VER}}" -X "generator.revision={{.Commit}}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - ppc64le
      - s390x
archive:
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
    - README.md
    - CHANGELOG.md
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
release:
  github:
    owner: ksonnet
    name: ksonnet
brew:
  github:
    owner: INVALID
    name: homebrew-tap
  commit_author:
    name: heptibot
    email: heptibot@heptio.com
  homepage: "https://ksonnet.io"
  description: "The ksonnet command line utility. Manage and deploy Kubernetes applications."
snapshot:
  name_template: SNAPSHOT-{{.Commit}}
