name: Docker

on:
  push:
    branches:
      - master
    paths:
      - '**/VERSION'
      - '**/Dockerfile'
jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

#  Environment variables does not work across differnet jobs
# https://github.com/actions/starter-workflows/issues/68#issuecomment-642514933
      - name: environment
        run: |
          echo "export DOCKER_REGISTRY_URL=ghcr.io" > ~/.bashrc
          echo "export REPOSITORY=jadia" >> ~/.bashrc
          echo "export USERNAME=jadia" >> ~/.bashrc


      - name: Log into registry
#       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login $DOCKER_REGISTRY_URL -u $USERNAME --password-stdin
        run: source ~/.bashrc; echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u jadia --password-stdin

      - name: Build and push the images
        run: |
          # Using the env var: https://github.com/actions/starter-workflows/issues/68#issuecomment-642514933
          source ~/.bashrc
          # The image is only build if changes is made in VERSION file of the application
          for versionFilePath in $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} ${{ github.event.before }} | grep "VERSION");
          do
            folder=${versionFilePath%"/VERSION"}
            IMAGE_NAME=${folder##*/}

            tmpName="image-$RANDOM"
            docker build $folder --file $folder/Dockerfile --tag $tmpName
            #IMAGE_ID=${{ secrets.DOCKER_REGISTRY_URL }}/$REPOSITORY/$IMAGE_NAME
            IMAGE_ID=$DOCKER_REGISTRY_URL/$GITHUB_REPOSITORY/$IMAGE_NAME
            VERSION=$(cat $versionFilePath)

            echo IMAGE_ID=$IMAGE_ID
            echo VERSION=$VERSION

            docker tag $tmpName $IMAGE_ID:$VERSION
            docker push $IMAGE_ID:$VERSION
            docker tag $IMAGE_ID:$VERSION $IMAGE_ID:latest
            docker push $IMAGE_ID:latest
          done;
